export enum AuthMethod {
  FB_EMAIL_PASSWORD = 'FB_EMAIL_PASSWORD',
  FB_GOOGLE = 'FB_GOOGLE',
  FB_FACEBOOK = 'FB_FACEBOOK',
  FB_TWITTER = 'FB_TWITTER',
  FB_GITHUB = 'FB_GITHUB',
  FB_MICROSOFT = 'FB_MICROSOFT',
  FB_APPLE = 'FB_APPLE',
  FB_PHONE = 'FB_PHONE',
  FB_ANONYMOUS = 'FB_ANONYMOUS',
}
